server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

#mybatis
mybatis:
  typeAliasesPackage: com.example.demo.domain
  mapper-locations: classpath:/sqlmap/*Mapper.xml

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
